spring:
  jpa:
    hibernate:
      ddl-auto: update 
  datasource:
    url: "jdbc:mysql://localhost/CREDITCARDSYSTEM"
    username: "root"
    password: "pass@word1"
  mail:
    host: smtp.gmail.com
    port: 587
    username: "XXXXXXXXXXXXXXXX"
    password: "XXXXXXXXXXXXXXXX" 
    properties:
      mail:
        auth: true
        starttls:
          enables: true
          required: true
  
    
server:
  port: ${PORT:0}
  
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}      