server:
  port: ${PORT:8761}
  
spring:
  application:    name: registry-server

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
